### ISSUE TITLE
Installing nkbase error

### ISSUE THREAD

**Issue by haroldvera** [Nekso/nkbase#6]
I have followed the site instruction to install 

git clone https://github.com/Nekso/nkbase.git
make

(I have erlang R17 installed)

with the result,

Compiled src/synctree_orddict.erl
Compiled src/synctree.erl
Compiled src/riak_ensemble_peer.erl
Compiling c_src/riak_ensemble_clock.c
==> pbkdf2 (compile)
ERROR: Cannot parse OTP Release version string: 17
ERROR: compile failed while processing /private/tmp/nkbase/deps/pbkdf2: rebar_abort
make: **\* [compile] Error 1

**Comment by cmeiklejohn** [comment]
Rebar needs to be updated to be aware of the change in versioning for Erlang, I believe.

**Comment by haroldvera** [comment]
I have the last version,

rebar --version
rebar 2.6.0 17 20150811_180118 git 2.6.0-16-g3239e74

and the error is the same,

ompiled src/synctree_ets.erl
Compiled src/synctree_leveldb.erl
Compiled src/synctree_orddict.erl
Compiled src/synctree.erl
Compiled src/riak_ensemble_peer.erl
Compiling c_src/riak_ensemble_clock.c
==> pbkdf2 (compile)
ERROR: Cannot parse OTP Release version string: 17
ERROR: compile failed while processing /private/tmp/nkbase/deps/pbkdf2: rebar_abort

**Comment by haroldvera** [comment]
Sorry, now i have changed github nkbase rebar by  rebar 2.6.0 and all worked like a charm. Thank you cmeiklejohn . issue closed. 

Current github nkbase rebar version is 2.1.0-pre-168-gaa46d85

**Comment by kalta** [comment]
Thank you, I will update the rebar version
