### ISSUE TITLE
is there a backup / restore facility

### ISSUE THREAD

**Issue by hwinkel** [Nekso/nkbase#7]
If you consider to use nkbase in production, is there a strategy to backup and restore data. Or do you follow the same priciples as riak:

http://docs.basho.com/riak/latest/ops/running/backups/
https://github.com/basho/leveldb/wiki/Repair-Notes

**Comment by kalta** [comment]
Hi, we don't yet have any backup strategy, but the Riak method should work ok, when it refers to LevelDB.

Thank you for the links
